---
- name: Prepare the VM on the test server
  hosts: ubuntu_host
  gather_facts: false
  vars:
    # Имя виртуалки для теста
    vm_name: win2k19-liw-test
    # Имя snapshot для отката виртуалки в исходное состояние
    vm_snapshot: snapshot1

  tasks:
    - name: Prompt for revert VM to source snpashot
      ansible.builtin.pause:
        prompt: "Откатить {{ vm_name }} к исходному снимку {{ vm_snapshot }}? (да/нет)"
      register: user_confirmation_vm

    - name: Revert VM to snapshot and start
      shell: |
        virsh snapshot-revert {{ vm_name }} {{ vm_snapshot }} --running --force
      become: true
      when: user_confirmation_vm.user_input | lower in yes_answer

    - name: Prompt for revert VM to source snpashot 2
      ansible.builtin.pause:
        prompt: "Откатить {{ vm_name }} к снимку {{ vm_snapshot_2 }}? (да/нет)"
      register: user_confirmation_vm

    - name: Revert VM to snapshot and start
      shell: |
        virsh snapshot-revert {{ vm_name }} {{ vm_snapshot_2 }} --running --force
      become: true
      when: user_confirmation_vm.user_input | lower in yes_answer

- name: Install LiW
  hosts: liwws2019
  gather_facts: false

  tasks:
    # Подготовка сервера
    - name: Prompt for preconfig
      pause:
        prompt: "Выполнить подготовку сервера? (да/нет)"
      register: user_confirmation_input1
      when: not all_install

    - name: Set answer
      set_fact:
        user_answer: "{{ user_confirmation_input1.user_input | lower }}"
      when: user_confirmation_input1.user_input is defined

    - name: "Подготовка сервера"
      include_role:
        name: preconfig
      when: (all_install | bool) or (user_answer in yes_answer)

    # Установка утилит для АНТОР админа сервера
    - name: Prompt for tools install
      pause:
        prompt: "Установить утилиты для администрирования сервера? (да/нет)"
      register: user_confirmation_input1
      when: not all_install

    - name: Set answer
      set_fact:
        user_answer: "{{ user_confirmation_input1.user_input | lower }}"
      when: user_confirmation_input1.user_input is defined

    - name: "Установка утилит"
      include_role:
        name: tools
      when: (all_install | bool) or (user_answer in yes_answer)

    # Установка роли IIS на сервере
    - name: Prompt for iis install
      pause:
        prompt: "Установить IIS? (да/нет)"
      register: user_confirmation_input1
      when: not all_install

    - name: Set answer
      set_fact:
        user_answer: "{{ user_confirmation_input1.user_input | lower }}"
      when: user_confirmation_input1.user_input is defined

    - name: "Установка IIS"
      include_role:
        name: iis
      when: (all_install | bool) or (user_answer in yes_answer)

    # Установка сайта АНТОР Enterprise
    - name: Prompt for ae-site install
      pause:
        prompt: "Установить AMTOR Enterprise site? (да/нет)"
      register: user_confirmation_input1
      when: not all_install

    - name: Set answer
      set_fact:
        user_answer: "{{ user_confirmation_input1.user_input | lower }}"
      when: user_confirmation_input1.user_input is defined

    - name: "Установка сайта ANTOR Enterprise"
      include_role:
        name: iis_ent_site
      when: (all_install | bool) or (user_answer in yes_answer)

    # Установка FTP
    - name: Prompt for FTP install
      pause:
        prompt: "Установить ANTOR FTP? (да/нет)"
      register: user_confirmation_input1
      when: not all_install

    - name: Set answer
      set_fact:
        user_answer: "{{ user_confirmation_input1.user_input | lower }}"
      when: user_confirmation_input1.user_input is defined

    - name: "Установка сайта ANTOR FTP"
      include_role:
        name: iis_ftp
      when: (all_install | bool) or (user_answer in yes_answer)

    # Установка WedDav
    - name: Prompt for WebDav install
      pause:
        prompt: "Установить WebDav? (да/нет)"
      register: user_confirmation_input1
      when: not all_install

    - name: Set answer
      set_fact:
        user_answer: "{{ user_confirmation_input1.user_input | lower }}"
      when: user_confirmation_input1.user_input is defined

    - name: "Установка сайта WebDav"
      include_role:
        name: iis_webdav
      when: (all_install | bool) or (user_answer in yes_answer)

    # Установка cервиса AEGatewayService
    - name: Prompt for AEGatewayService install
      pause:
        prompt: "Установить AEGatewayService? (да/нет)"
      register: user_confirmation_input1
      when: not all_install

    - name: Set answer
      set_fact:
        user_answer: "{{ user_confirmation_input1.user_input | lower }}"
      when: user_confirmation_input1.user_input is defined

    - name: "Установка сайта AEGatewayService"
      include_role:
        name: ae_gateway
      when: (all_install | bool) or (user_answer in yes_answer)
