---
- name: Prepare the VM on the test server
  hosts: ubuntu_host
  vars:
    # Имя виртуалки для теста
    vm_name: win2k19-liw-test
    # Имя snapshot для отката виртуалки в исходное состояние
    vm_snapshot: snapshot1
  tasks:
    - name: Prompt for revert VM to source snpashot
      ansible.builtin.pause:
        prompt: "Откатить {{ vm_name }} к исходному снимку {{ vm_snapshot }}? (да/нет):"
        echo: true
      register: user_confirmation_vm
    - name: Revert VM to snapshot and start
      shell: |
        virsh snapshot-revert {{ vm_name }} {{ vm_snapshot }} --force
      become: true
      when: user_confirmation_vm | lower = 'да'

- name: Install LiW
  hosts: liwws2019
  roles:
    - preconfig
    - tools
