---
- name: test
  hosts: liwws2019  
  gather_facts: no 

  vars:
    antor_ent_site: "ANTOR Enterprise"

    cert_7z_file: "Certificates.7z"
    cert_folder: "Certificates"
 

  tasks:  
    - name: add firewall rule ANTOR Webdav
      win_firewall_rule:
        name: "ANTOR WebDav Port"
        direction: in
        action: Allow
        protocol: TCP
        localport: "8101, 8102"
        state: present
        enabled: yes
        profile:
          - Domain
          - Private
          - Public
