#Certificates
cert_7z_file: "Certificates.7z"
cert_folder: "Certificates"
root_cert_passw: "andrewgor"
antor_root_authotity_file: "ANTOR Enterprise Root Authority.pfx"
antor_root_authotity: "ANTOR Enterprise Root Authority"