- name: AE site install
  include_role:
    name: iis_ent_site
  when: not iis_ent_site_installed

- name: 7z liw services and baks on repo host
  shell: 7z a -r -up1q1r2x1y1z1w1 ~/{{ repo_liws_7z }} {{ repo_liw_services_mnt }}/
  register: q1
  delegate_to: 127.0.0.1
  run_once: true
  #tags: test

- name: Copy 7z file liw services to target host
  win_copy:
    src: ~/{{ repo_liws_7z }}
    dest: "{{ distr_folder_host }}\\{{ repo_liws_7z }}"
  #tags: test

- name: Extract liw services and baks
  win_shell: 7z x "{{ distr_folder_host }}\\{{ repo_liws_7z }}" -o"{{ distr_folder_host }}" -aos
  #tags: test

- name: Create directories
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop: "{{ liw_services_list | map(attribute='install_dir') | list  + [db_folder_host , db_log_dir , db_data_dir, avalon_dir, webpages_dir] }}"
  #tags: test

- name: Add share
  win_share:
    name: "{{ avalon_dir }}"
    description: " Share {{ avalon_dir }}"
    path: "{{ avalon_dir }}"
    full: Everyone
  #tags: test

- name: Set rights liw services folder
  win_acl:
    path: "{{ item }}"
    user: "{{ user_antor }}"
    rights: FullControl
    state: present
    type: allow
  loop: "{{ liw_services_list | map(attribute='install_dir') | list  + [db_folder_host , db_log_dir , db_data_dir] }}"
  #tags: test

- name: Add user to SQL server
  win_shell: |
    $un = "{{ host_name }}\{{ user_antor }}"
    $connString = "Server='{{ sql_host }}\{{ sql_name }}';Database='master';Integrated Security=True;"
    $sql = "IF NOT EXISTS (SELECT * FROM sys.server_principals WHERE name = N'$un') `
      BEGIN CREATE LOGIN [$un] FROM WINDOWS WITH DEFAULT_DATABASE=[master]; ALTER SERVER ROLE [sysadmin] ADD MEMBER [$un] END"
    Invoke-Sqlcmd -ConnectionString $connString -Query $sql -QueryTimeout 0
  #tags: test

- name: Restore liw services databases
  win_shell: |
    $connString = "Server='{{ sql_host }}\{{ sql_name }}';Database='master';Integrated Security=True;"
    $file = "{{liw_services_distr_bak }}\{{ item.bak_file }}"
    $lfd = "{{ item.log_names[0] }}"
    $lfl = "{{ item.log_names[1] }}"
    $data_dir_file = "{{ db_data_dir }}\{{ item.mdf_name }}"
    $log_dir_file = "{{ db_log_dir }}\{{ item.ldf_name }}"    
    $db_name = "{{ item.db_name }}"
    $sql = "IF NOT EXISTS (SELECT name FROM master.dbo.sysdatabases WHERE name = N'$db_name')  `
      BEGIN RESTORE DATABASE [$db_name] FROM DISK = '$file' WITH REPLACE, RECOVERY, MOVE '${lfd}' TO '${data_dir_file}.mdf',   MOVE '${lfl}' TO '${log_dir_file}.ldf' END"    
    Invoke-Sqlcmd -ConnectionString $connString -Query $sql -QueryTimeout 0
  loop: "{{ db_list }}"
  #tags: test

- name: Prepare SQL files
  win_shell: (Get-Content -Path "{{ liw_services_distr_bak }}\{{ item.0.1 }}").replace('{{ item.1.0 }}','{{ item.1.1 }}') | Set-Content -Path "{{ liw_services_distr_bak }}\{{ item.0.1 }}"
  loop: "{{ db_list | subelements('spec_sql', skip_missing=True) | product(replace_str_list | zip(value_str_list) | list) | list }}"
  tags: test

- name: Copy files for liw services to IIS folder
  community.windows.win_robocopy:
    src: "{{ liw_services_distr }}\\{{ item.name }}\\"
    dest: "{{ item.install_dir }}"
    purge: true 
    flags: /MIR
    recurse: true
  loop: "{{ liw_services_list }}"
  tags: test

- name: Set configs liw services
  community.windows.win_xml:
    path: "{{ item.0.install_dir }}\\{{item.0.config_file}}"
    xpath: "{{ item.1.xpath }}"
    fragment: "{{ item.1.value | trim }}"
    type: "{{ item.1.type }}"
    attribute: "{{ item.1.attribute }}"
    state: present
    text: "{{ item.1.text }}"
  loop: "{{ lookup('ansible.builtin.subelements', liw_services_list, 'config_change') }}"
  tags: test

- name: Add web application
  win_shell: |
    New-WebApplication -Name {{ item.webapp_name }} -Site "{{ antor_ent_site }}" -PhysicalPath "{{ item.install_dir }}" -ApplicationPool "{{ antor_ent_site }}"
  register: r1  
  loop: "{{ liw_services_list }}"
  failed_when: r1.rc != 0 and 'Destination element already exists' not in r1.stderr
  tags: test

- name: Test liw services
  shell: "{{ item.1 }}"
  loop: "{{ liw_services_list | subelements('test_command') }}"
  delegate_to: 127.0.0.1
  register: test_liw_services
  loop_control:
    label: "{{ item.1 }}"
  tags: test

- name: Display the results of the test loop
  ansible.builtin.debug:
    msg: "{{ item.cmd }} : \n\n {{ item.stdout }}"
  loop: "{{ test_liw_services.results }}"
  loop_control:
    label: "{{ item.cmd }}"
  tags: test

- name: Set fact component installed
  set_fact:
    liw_services_installed: true
  tags: test
